### ISSUE TITLE
create minimal environment for microservices 🍻

### ISSUE THREAD

**Issue by tokuchar** [parkingology/parking-dev-env#3]
with Jenkinsfile and docker-compose create:
- ELK stack
- harbor
- jeager (this one maybe should be running with ELK on the same elastic)
- rabbitMQ

++stage to **test** if each part of the env responds correctly ;)

**Comment by tokuchar** [comment]
to run docker from jenkins (on the same docker host) whe must create **DID** (docker in docker)
https://shisho.dev/blog/posts/docker-in-docker/

follow the instruction for debian, but you must install only `docker-ce`:
https://docs.docker.com/engine/install/debian/
and inside root user in docker we must:
```
chmod 777 /var/run/docker.sock
```

**Comment by tokuchar** [comment]
https://stackoverflow.com/questions/43183495/how-to-dynamically-pick-a-git-branch-to-use-in-jenkins-build

**Comment by KleczkoPawel** [comment]
**[Jenkins]** Working on dynamically branch picking.

**Comment by KleczkoPawel** [comment]
**[Jenkins]** Dynamically branch picking option has been added.

**Comment by tokuchar** [comment]
to install `docker-compose`:
```sh
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```
```sh
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by tokuchar** [comment]
```yml  
logstash:
    container_name: logstash
    image: logstash:7.16.3
    ports:
      - '5002:5000'
      - '9600:9600'
    volumes:
      - type: bind
        source: /home/opc/jenkins_data
```
`/home/opc/jenkins_data` must be mapped in jenkins container and **OCI** and `ports.conf` must be moved by jenkins to this dir
